name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake pkg-config libraylib-dev
      
      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake ..
          make -j$(nproc)
      
      - name: Package
        run: |
          mkdir -p dist/linux
          cp build/crist-project dist/linux/
          cp -r assets dist/linux/
          cd dist
          tar -czf crist-project-linux.tar.gz linux
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: crist-project-linux
          path: dist/crist-project-linux.tar.gz
      
      - name: Upload release assets
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: dist/crist-project-linux.tar.gz
  
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            git
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-make
            mingw-w64-x86_64-raylib
      
      - name: Build
        shell: msys2 {0}
        run: |
          mkdir -p build
          cd build
          cmake .. -G "MSYS Makefiles"
          make -j$(nproc)
      
      - name: Package
        shell: msys2 {0}
        run: |
          mkdir -p dist/windows
          cp build/crist-project.exe dist/windows/
          cp -r assets dist/windows/
          cd dist
          7z a crist-project-windows.zip windows
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: crist-project-windows
          path: dist/crist-project-windows.zip
      
      - name: Upload release assets
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: dist/crist-project-windows.zip
